export enum FeatureNames {
  MANAGE_LEADS = 'Manage Leads and Customer Data',
  TEAM_MEMBERS = 'Add and Manage Team Members',
  QUICK_REPLY = 'Create Quick Reply Message Templates',
  CUSTOM_TAGS = 'Organize Leads Using Custom Tags',
  SALES_PIPELINE = 'Track Sales Pipeline and Progress',
  SUPPORT_TICKETS = 'Manage and Track Support Tickets',
  BUSINESS_INSIGHTS = 'Access Business Insights Dashboard',
  EXPORT_DATA = 'Export Business Reports and Data',
  BULK_IMPORT = 'Bulk Import Leads from CSV File',
  TASK_REMINDERS = 'Set and Manage Task Reminders',
  BUSINESS_EVENTS = 'Schedule and Manage Business Events',
  GOOGLE_DRIVE = 'Sync Files with Google Drive',
  MANAGE_DEPARTMENTS = 'Create and Manage Departments Easily',
  STORE_IMAGES = 'Save and Store Business Images',
  SYNC_CONVERSATIONS = 'Sync Conversations Across Multiple Devices',
  FACEBOOK_LEAD = 'Integrate and Manage Facebook Lead',
  GOOGLE_CALENDAR = 'Sync Events with Google Calendar',
}
